export const mockRestaurants = [
  {
    _id: 'rest_001',
    name: 'Chicken Inn',
    description: 'Zimbabwe\'s favorite fried chicken. Crispy, juicy, and always fresh.',
    cuisine: ['Fast Food', 'Chicken', 'African'],
    rating: 4.5,
    reviewCount: 1250,
    priceRange: '$$',
    deliveryFee: 2,
    minimumOrder: 5,
    imageUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
    coverImage: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800',
    location: {
      address: 'Sam Levy Village, Borrowdale, Harare',
      latitude: -17.7634,
      longitude: 31.0756,
    },
    contactPhone: '+263771234567',
    contactWhatsApp: '+263771234567',
    isOpen: true,
    openingHours: {
      monday: { open: '08:00', close: '22:00' },
      tuesday: { open: '08:00', close: '22:00' },
      wednesday: { open: '08:00', close: '22:00' },
      thursday: { open: '08:00', close: '22:00' },
      friday: { open: '08:00', close: '23:00' },
      saturday: { open: '08:00', close: '23:00' },
      sunday: { open: '09:00', close: '21:00' },
    },
    featured: true,
    acceptsBidding: true,
    preparationTime: 20,
    status: 'active',
  },
  {
    _id: 'rest_002',
    name: 'Nando\'s',
    description: 'Flame-grilled PERi-PERi chicken. Famous for our signature sauces.',
    cuisine: ['Portuguese', 'Chicken', 'African'],
    rating: 4.6,
    reviewCount: 980,
    priceRange: '$$$',
    deliveryFee: 3,
    minimumOrder: 8,
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400',
    coverImage: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800',
    location: {
      address: 'Avondale Shopping Centre, Harare',
      latitude: -17.7892,
      longitude: 31.0345,
    },
    contactPhone: '+263772345678',
    contactWhatsApp: '+263772345678',
    isOpen: true,
    openingHours: {
      monday: { open: '10:00', close: '22:00' },
      tuesday: { open: '10:00', close: '22:00' },
      wednesday: { open: '10:00', close: '22:00' },
      thursday: { open: '10:00', close: '22:00' },
      friday: { open: '10:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    featured: true,
    acceptsBidding: true,
    preparationTime: 25,
    status: 'active',
  },
  {
    _id: 'rest_003',
    name: 'Galito\'s',
    description: 'Flame-grilled chicken with African flavors. Quality you can taste.',
    cuisine: ['Fast Food', 'Chicken', 'African'],
    rating: 4.3,
    reviewCount: 756,
    priceRange: '$$',
    deliveryFee: 2,
    minimumOrder: 5,
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400',
    coverImage: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
    location: {
      address: 'Joina City, CBD, Harare',
      latitude: -17.8292,
      longitude: 31.0522,
    },
    contactPhone: '+263773456789',
    contactWhatsApp: '+263773456789',
    isOpen: true,
    openingHours: {
      monday: { open: '08:00', close: '20:00' },
      tuesday: { open: '08:00', close: '20:00' },
      wednesday: { open: '08:00', close: '20:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '21:00' },
      saturday: { open: '08:00', close: '21:00' },
      sunday: { open: '09:00', close: '18:00' },
    },
    featured: false,
    acceptsBidding: true,
    preparationTime: 20,
    status: 'active',
  },
  {
    _id: 'rest_004',
    name: 'Debonairs Pizza',
    description: 'Triple-decker pizzas and more. Real pizza, real people.',
    cuisine: ['Pizza', 'Italian', 'Fast Food'],
    rating: 4.4,
    reviewCount: 890,
    priceRange: '$$',
    deliveryFee: 2.5,
    minimumOrder: 10,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    coverImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    location: {
      address: 'Eastgate Mall, Harare',
      latitude: -17.8156,
      longitude: 31.0778,
    },
    contactPhone: '+263774567890',
    contactWhatsApp: '+263774567890',
    isOpen: true,
    openingHours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    featured: true,
    acceptsBidding: true,
    preparationTime: 30,
    status: 'active',
  },
  {
    _id: 'rest_005',
    name: 'Spur Steak Ranches',
    description: 'Family restaurant with flame-grilled steaks and ribs.',
    cuisine: ['Steakhouse', 'American', 'Family'],
    rating: 4.2,
    reviewCount: 620,
    priceRange: '$$$',
    deliveryFee: 3,
    minimumOrder: 15,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    location: {
      address: 'Westgate Shopping Centre, Harare',
      latitude: -17.7956,
      longitude: 30.9876,
    },
    contactPhone: '+263775678901',
    contactWhatsApp: '+263775678901',
    isOpen: true,
    openingHours: {
      monday: { open: '11:00', close: '22:00' },
      tuesday: { open: '11:00', close: '22:00' },
      wednesday: { open: '11:00', close: '22:00' },
      thursday: { open: '11:00', close: '22:00' },
      friday: { open: '11:00', close: '23:00' },
      saturday: { open: '11:00', close: '23:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    featured: false,
    acceptsBidding: true,
    preparationTime: 35,
    status: 'active',
  },
  {
    _id: 'rest_006',
    name: 'Tandoori Kitchen',
    description: 'Authentic Indian cuisine. Curries, biryanis, and tandoori specialties.',
    cuisine: ['Indian', 'Curry', 'Asian'],
    rating: 4.7,
    reviewCount: 445,
    priceRange: '$$$',
    deliveryFee: 3,
    minimumOrder: 12,
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    coverImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    location: {
      address: 'Chisipite Shopping Centre, Harare',
      latitude: -17.7567,
      longitude: 31.1034,
    },
    contactPhone: '+263776789012',
    contactWhatsApp: '+263776789012',
    isOpen: true,
    openingHours: {
      monday: { open: '11:00', close: '21:30' },
      tuesday: { open: '11:00', close: '21:30' },
      wednesday: { open: '11:00', close: '21:30' },
      thursday: { open: '11:00', close: '21:30' },
      friday: { open: '11:00', close: '22:30' },
      saturday: { open: '11:00', close: '22:30' },
      sunday: { open: '12:00', close: '21:00' },
    },
    featured: true,
    acceptsBidding: true,
    preparationTime: 30,
    status: 'active',
  },
  {
    _id: 'rest_007',
    name: 'Golden Dragon',
    description: 'Chinese cuisine at its finest. Dim sum, noodles, and stir-fries.',
    cuisine: ['Chinese', 'Asian', 'Noodles'],
    rating: 4.4,
    reviewCount: 380,
    priceRange: '$$',
    deliveryFee: 2.5,
    minimumOrder: 10,
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400',
    coverImage: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
    location: {
      address: 'Newlands Shopping Centre, Harare',
      latitude: -17.7789,
      longitude: 31.0567,
    },
    contactPhone: '+263777890123',
    contactWhatsApp: '+263777890123',
    isOpen: true,
    openingHours: {
      monday: { open: '10:00', close: '21:30' },
      tuesday: { open: '10:00', close: '21:30' },
      wednesday: { open: '10:00', close: '21:30' },
      thursday: { open: '10:00', close: '21:30' },
      friday: { open: '10:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    featured: false,
    acceptsBidding: true,
    preparationTime: 25,
    status: 'active',
  },
  {
    _id: 'rest_008',
    name: 'Mugg & Bean',
    description: 'Coffee house with all-day breakfast, burgers, and baked goods.',
    cuisine: ['Cafe', 'Breakfast', 'Coffee'],
    rating: 4.3,
    reviewCount: 520,
    priceRange: '$$',
    deliveryFee: 2,
    minimumOrder: 8,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    location: {
      address: 'Sam Levy Village, Borrowdale, Harare',
      latitude: -17.7645,
      longitude: 31.0767,
    },
    contactPhone: '+263778901234',
    contactWhatsApp: '+263778901234',
    isOpen: true,
    openingHours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '21:00' },
      saturday: { open: '07:30', close: '21:00' },
      sunday: { open: '08:00', close: '18:00' },
    },
    featured: false,
    acceptsBidding: true,
    preparationTime: 20,
    status: 'active',
  },
  {
    _id: 'rest_009',
    name: 'Mama Mia\'s Kitchen',
    description: 'Traditional Zimbabwean dishes. Sadza, nyama, and muriwo.',
    cuisine: ['African', 'Zimbabwean', 'Traditional'],
    rating: 4.6,
    reviewCount: 340,
    priceRange: '$',
    deliveryFee: 1.5,
    minimumOrder: 5,
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400',
    coverImage: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800',
    location: {
      address: 'Mbare Musika, Harare',
      latitude: -17.8567,
      longitude: 31.0423,
    },
    contactPhone: '+263779012345',
    contactWhatsApp: '+263779012345',
    isOpen: true,
    openingHours: {
      monday: { open: '06:00', close: '20:00' },
      tuesday: { open: '06:00', close: '20:00' },
      wednesday: { open: '06:00', close: '20:00' },
      thursday: { open: '06:00', close: '20:00' },
      friday: { open: '06:00', close: '21:00' },
      saturday: { open: '06:00', close: '21:00' },
      sunday: { open: '07:00', close: '18:00' },
    },
    featured: true,
    acceptsBidding: true,
    preparationTime: 25,
    status: 'active',
  },
  {
    _id: 'rest_010',
    name: 'Steers',
    description: 'Flame-grilled burgers and ribs. Real food, made real good.',
    cuisine: ['Burgers', 'Fast Food', 'American'],
    rating: 4.2,
    reviewCount: 678,
    priceRange: '$$',
    deliveryFee: 2,
    minimumOrder: 6,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    coverImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    location: {
      address: 'Borrowdale Village, Harare',
      latitude: -17.7512,
      longitude: 31.0823,
    },
    contactPhone: '+263770123456',
    contactWhatsApp: '+263770123456',
    isOpen: true,
    openingHours: {
      monday: { open: '09:00', close: '22:00' },
      tuesday: { open: '09:00', close: '22:00' },
      wednesday: { open: '09:00', close: '22:00' },
      thursday: { open: '09:00', close: '22:00' },
      friday: { open: '09:00', close: '23:00' },
      saturday: { open: '09:00', close: '23:00' },
      sunday: { open: '10:00', close: '21:00' },
    },
    featured: false,
    acceptsBidding: true,
    preparationTime: 20,
    status: 'active',
  },
  {
    _id: 'rest_011',
    name: 'Ocean Basket',
    description: 'Fresh seafood restaurant. Fish, prawns, calamari, and more.',
    cuisine: ['Seafood', 'Fish', 'Mediterranean'],
    rating: 4.5,
    reviewCount: 290,
    priceRange: '$$$',
    deliveryFee: 3.5,
    minimumOrder: 15,
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
    coverImage: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    location: {
      address: 'Arundel Village, Mount Pleasant, Harare',
      latitude: -17.7734,
      longitude: 31.0456,
    },
    contactPhone: '+263771234560',
    contactWhatsApp: '+263771234560',
    isOpen: true,
    openingHours: {
      monday: { open: '11:00', close: '21:30' },
      tuesday: { open: '11:00', close: '21:30' },
      wednesday: { open: '11:00', close: '21:30' },
      thursday: { open: '11:00', close: '21:30' },
      friday: { open: '11:00', close: '22:00' },
      saturday: { open: '11:00', close: '22:00' },
      sunday: { open: '12:00', close: '21:00' },
    },
    featured: false,
    acceptsBidding: true,
    preparationTime: 30,
    status: 'active',
  },
  {
    _id: 'rest_012',
    name: 'Wimpy',
    description: 'Family-friendly burgers and breakfast. Since 1967.',
    cuisine: ['Burgers', 'Breakfast', 'Fast Food'],
    rating: 4.0,
    reviewCount: 890,
    priceRange: '$$',
    deliveryFee: 2,
    minimumOrder: 5,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
    coverImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
    location: {
      address: 'First Street Mall, CBD, Harare',
      latitude: -17.8312,
      longitude: 31.0534,
    },
    contactPhone: '+263772345670',
    contactWhatsApp: '+263772345670',
    isOpen: true,
    openingHours: {
      monday: { open: '07:00', close: '21:00' },
      tuesday: { open: '07:00', close: '21:00' },
      wednesday: { open: '07:00', close: '21:00' },
      thursday: { open: '07:00', close: '21:00' },
      friday: { open: '07:00', close: '22:00' },
      saturday: { open: '08:00', close: '22:00' },
      sunday: { open: '08:00', close: '20:00' },
    },
    featured: false,
    acceptsBidding: true,
    preparationTime: 15,
    status: 'active',
  },
];

export const mockMenuItems = [
  // Chicken Inn Menu
  {
    _id: 'menu_001',
    restaurantId: 'rest_001',
    name: '2 Piece Chicken & Chips',
    description: 'Two pieces of crispy fried chicken with golden chips',
    price: 5.50,
    category: 'Chicken Meals',
    imageUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 10,
    customizations: [],
  },
  {
    _id: 'menu_002',
    restaurantId: 'rest_001',
    name: '4 Piece Chicken Bucket',
    description: 'Four pieces of our famous crispy fried chicken',
    price: 9.00,
    category: 'Chicken Meals',
    imageUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 12,
    customizations: [
      {
        name: 'Add Coleslaw',
        type: 'checkbox',
        required: false,
        options: [{ name: 'Coleslaw', price: 1.00 }],
      },
    ],
  },
  {
    _id: 'menu_003',
    restaurantId: 'rest_001',
    name: 'Chicken Burger',
    description: 'Crispy chicken fillet in a soft bun with lettuce and mayo',
    price: 4.50,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 8,
    customizations: [
      {
        name: 'Make it a meal',
        type: 'checkbox',
        required: false,
        options: [{ name: 'Add Chips & Drink', price: 2.50 }],
      },
    ],
  },
  {
    _id: 'menu_004',
    restaurantId: 'rest_001',
    name: 'Large Chips',
    description: 'Golden crispy chips - large portion',
    price: 2.50,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1630384060421-cb20aed9d7d8?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 5,
    customizations: [],
  },
  {
    _id: 'menu_005',
    restaurantId: 'rest_001',
    name: 'Coca-Cola 500ml',
    description: 'Ice-cold Coca-Cola',
    price: 1.50,
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 1,
    customizations: [],
  },

  // Nando's Menu
  {
    _id: 'menu_006',
    restaurantId: 'rest_002',
    name: 'Quarter Chicken',
    description: 'PERi-PERi flame-grilled chicken - leg or breast',
    price: 6.00,
    category: 'Chicken',
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 15,
    customizations: [
      {
        name: 'Portion',
        type: 'radio',
        required: true,
        options: [
          { name: 'Leg', price: 0 },
          { name: 'Breast', price: 1.00 },
        ],
      },
      {
        name: 'PERi-PERi Level',
        type: 'radio',
        required: true,
        options: [
          { name: 'Plain...ish', price: 0 },
          { name: 'Lemon & Herb', price: 0 },
          { name: 'Medium', price: 0 },
          { name: 'Hot', price: 0 },
          { name: 'Extra Hot', price: 0 },
        ],
      },
    ],
  },
  {
    _id: 'menu_007',
    restaurantId: 'rest_002',
    name: 'Half Chicken',
    description: 'Half a PERi-PERi flame-grilled chicken',
    price: 10.00,
    category: 'Chicken',
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 18,
    customizations: [
      {
        name: 'PERi-PERi Level',
        type: 'radio',
        required: true,
        options: [
          { name: 'Plain...ish', price: 0 },
          { name: 'Lemon & Herb', price: 0 },
          { name: 'Medium', price: 0 },
          { name: 'Hot', price: 0 },
          { name: 'Extra Hot', price: 0 },
        ],
      },
    ],
  },
  {
    _id: 'menu_008',
    restaurantId: 'rest_002',
    name: 'Chicken Wings (8 pieces)',
    description: 'Flame-grilled chicken wings tossed in PERi-PERi',
    price: 8.00,
    category: 'Wings & Starters',
    imageUrl: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 12,
    customizations: [],
  },
  {
    _id: 'menu_009',
    restaurantId: 'rest_002',
    name: 'PERi-PERi Chips',
    description: 'Crispy chips sprinkled with PERi-PERi salt',
    price: 3.00,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1630384060421-cb20aed9d7d8?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 5,
    customizations: [],
  },

  // Debonairs Pizza Menu
  {
    _id: 'menu_010',
    restaurantId: 'rest_004',
    name: 'Triple-Decker Hawaiian',
    description: 'Three layers of ham, pineapple, and cheese',
    price: 15.00,
    category: 'Triple-Decker Pizzas',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 20,
    customizations: [
      {
        name: 'Size',
        type: 'radio',
        required: true,
        options: [
          { name: 'Medium', price: 0 },
          { name: 'Large', price: 4.00 },
          { name: 'Extra Large', price: 7.00 },
        ],
      },
    ],
  },
  {
    _id: 'menu_011',
    restaurantId: 'rest_004',
    name: 'Something Meaty',
    description: 'Bacon, beef, ham, pepperoni, and salami',
    price: 16.00,
    category: 'Classic Pizzas',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 18,
    customizations: [
      {
        name: 'Size',
        type: 'radio',
        required: true,
        options: [
          { name: 'Medium', price: 0 },
          { name: 'Large', price: 4.00 },
          { name: 'Extra Large', price: 7.00 },
        ],
      },
    ],
  },
  {
    _id: 'menu_012',
    restaurantId: 'rest_004',
    name: 'Margherita',
    description: 'Classic tomato base with mozzarella cheese',
    price: 10.00,
    category: 'Classic Pizzas',
    imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 15,
    customizations: [
      {
        name: 'Size',
        type: 'radio',
        required: true,
        options: [
          { name: 'Medium', price: 0 },
          { name: 'Large', price: 3.00 },
          { name: 'Extra Large', price: 5.00 },
        ],
      },
    ],
  },
  {
    _id: 'menu_013',
    restaurantId: 'rest_004',
    name: 'Crumbed Chicken Strips',
    description: 'Crispy chicken strips with dipping sauce',
    price: 5.00,
    category: 'Starters',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 10,
    customizations: [],
  },

  // Tandoori Kitchen Menu
  {
    _id: 'menu_014',
    restaurantId: 'rest_006',
    name: 'Butter Chicken',
    description: 'Creamy tomato-based curry with tender chicken',
    price: 12.00,
    category: 'Curries',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 20,
    customizations: [
      {
        name: 'Spice Level',
        type: 'radio',
        required: true,
        options: [
          { name: 'Mild', price: 0 },
          { name: 'Medium', price: 0 },
          { name: 'Hot', price: 0 },
        ],
      },
    ],
  },
  {
    _id: 'menu_015',
    restaurantId: 'rest_006',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice with spiced chicken',
    price: 11.00,
    category: 'Biryanis',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 25,
    customizations: [],
  },
  {
    _id: 'menu_016',
    restaurantId: 'rest_006',
    name: 'Garlic Naan',
    description: 'Soft naan bread with garlic butter',
    price: 2.50,
    category: 'Breads',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 8,
    customizations: [],
  },
  {
    _id: 'menu_017',
    restaurantId: 'rest_006',
    name: 'Vegetable Samosas (4 pcs)',
    description: 'Crispy pastry filled with spiced vegetables',
    price: 4.00,
    category: 'Starters',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 10,
    customizations: [],
  },

  // Mama Mia's Kitchen (Zimbabwean)
  {
    _id: 'menu_018',
    restaurantId: 'rest_009',
    name: 'Sadza & Beef Stew',
    description: 'Traditional sadza with rich beef stew and vegetables',
    price: 6.00,
    category: 'Main Dishes',
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 15,
    customizations: [],
  },
  {
    _id: 'menu_019',
    restaurantId: 'rest_009',
    name: 'Sadza & Chicken',
    description: 'Sadza served with delicious chicken pieces and gravy',
    price: 7.00,
    category: 'Main Dishes',
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 15,
    customizations: [
      {
        name: 'Chicken Type',
        type: 'radio',
        required: true,
        options: [
          { name: 'Grilled', price: 0 },
          { name: 'Fried', price: 0.50 },
        ],
      },
    ],
  },
  {
    _id: 'menu_020',
    restaurantId: 'rest_009',
    name: 'Sadza & Kapenta',
    description: 'Sadza with dried kapenta fish and tomato relish',
    price: 5.00,
    category: 'Main Dishes',
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 12,
    customizations: [],
  },
  {
    _id: 'menu_021',
    restaurantId: 'rest_009',
    name: 'Muriwo (Collard Greens)',
    description: 'Traditional Zimbabwean vegetables with peanut butter',
    price: 2.50,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 8,
    customizations: [],
  },

  // Steers Menu
  {
    _id: 'menu_022',
    restaurantId: 'rest_010',
    name: 'King Steer Burger',
    description: 'Flame-grilled 100% beef patty with cheese, bacon, and sauces',
    price: 8.00,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 12,
    customizations: [
      {
        name: 'Make it a meal',
        type: 'checkbox',
        required: false,
        options: [{ name: 'Add Chips & Drink', price: 3.00 }],
      },
    ],
  },
  {
    _id: 'menu_023',
    restaurantId: 'rest_010',
    name: 'Rib Burger',
    description: 'Flame-grilled rib patty with BBQ sauce',
    price: 7.50,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 12,
    customizations: [],
  },
  {
    _id: 'menu_024',
    restaurantId: 'rest_010',
    name: 'Wacky Wednesday 2 Burgers',
    description: 'Two flame-grilled burgers special deal',
    price: 10.00,
    category: 'Specials',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 15,
    customizations: [],
  },

  // Golden Dragon (Chinese)
  {
    _id: 'menu_025',
    restaurantId: 'rest_007',
    name: 'Sweet & Sour Chicken',
    description: 'Crispy chicken in tangy sweet and sour sauce',
    price: 9.00,
    category: 'Chicken',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 15,
    customizations: [],
  },
  {
    _id: 'menu_026',
    restaurantId: 'rest_007',
    name: 'Beef Chow Mein',
    description: 'Stir-fried noodles with beef and vegetables',
    price: 8.50,
    category: 'Noodles',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 12,
    customizations: [],
  },
  {
    _id: 'menu_027',
    restaurantId: 'rest_007',
    name: 'Egg Fried Rice',
    description: 'Wok-fried rice with egg and spring onions',
    price: 4.00,
    category: 'Rice',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 8,
    customizations: [],
  },
  {
    _id: 'menu_028',
    restaurantId: 'rest_007',
    name: 'Spring Rolls (4 pcs)',
    description: 'Crispy vegetable spring rolls with dipping sauce',
    price: 4.50,
    category: 'Starters',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 8,
    customizations: [],
  },

  // Mugg & Bean
  {
    _id: 'menu_029',
    restaurantId: 'rest_008',
    name: 'Big Breakfast',
    description: 'Eggs, bacon, sausage, mushrooms, tomato, and toast',
    price: 9.00,
    category: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 15,
    customizations: [
      {
        name: 'Eggs Style',
        type: 'radio',
        required: true,
        options: [
          { name: 'Fried', price: 0 },
          { name: 'Scrambled', price: 0 },
          { name: 'Poached', price: 0 },
        ],
      },
    ],
  },
  {
    _id: 'menu_030',
    restaurantId: 'rest_008',
    name: 'Club Sandwich',
    description: 'Triple-decker with chicken, bacon, lettuce, and tomato',
    price: 7.50,
    category: 'Sandwiches',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300',
    isAvailable: true,
    isVegetarian: false,
    preparationTime: 12,
    customizations: [],
  },
  {
    _id: 'menu_031',
    restaurantId: 'rest_008',
    name: 'Cappuccino',
    description: 'Rich espresso with steamed milk foam',
    price: 3.50,
    category: 'Hot Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 5,
    customizations: [
      {
        name: 'Size',
        type: 'radio',
        required: true,
        options: [
          { name: 'Regular', price: 0 },
          { name: 'Large', price: 1.00 },
        ],
      },
    ],
  },
  {
    _id: 'menu_032',
    restaurantId: 'rest_008',
    name: 'Chocolate Brownie',
    description: 'Warm chocolate brownie with vanilla ice cream',
    price: 5.00,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300',
    isAvailable: true,
    isVegetarian: true,
    preparationTime: 5,
    customizations: [],
  },
];

export const cuisineCategories = [
  'All',
  'Fast Food',
  'Chicken',
  'Pizza',
  'Burgers',
  'African',
  'Indian',
  'Chinese',
  'Seafood',
  'Cafe',
  'Steakhouse',
];

export const getRestaurantById = (id) => {
  return mockRestaurants.find((r) => r._id === id) || null;
};

export const getMenuByRestaurantId = (restaurantId) => {
  return mockMenuItems.filter((item) => item.restaurantId === restaurantId);
};

export const getMenuItemById = (id) => {
  return mockMenuItems.find((item) => item._id === id) || null;
};

export const searchRestaurants = (query) => {
  const lowerQuery = query.toLowerCase();
  return mockRestaurants.filter(
    (r) =>
      r.name.toLowerCase().includes(lowerQuery) ||
      r.description.toLowerCase().includes(lowerQuery) ||
      r.cuisine.some((c) => c.toLowerCase().includes(lowerQuery))
  );
};

export const filterRestaurants = (filters = {}) => {
  let results = [...mockRestaurants];

  if (filters.cuisine && filters.cuisine !== 'All') {
    results = results.filter((r) =>
      r.cuisine.some((c) => c.toLowerCase() === filters.cuisine.toLowerCase())
    );
  }

  if (filters.isOpen !== undefined) {
    results = results.filter((r) => r.isOpen === filters.isOpen);
  }

  if (filters.featured) {
    results = results.filter((r) => r.featured === true);
  }

  if (filters.minRating) {
    results = results.filter((r) => r.rating >= filters.minRating);
  }

  if (filters.priceRange) {
    results = results.filter((r) => r.priceRange === filters.priceRange);
  }

  return results;
};

